# Podfile for TryAngle iOS App
platform :ios, '15.0'

project 'TryAngleApp/TryAngleApp.xcodeproj'

target 'TryAngleApp' do
  use_frameworks!

  # ONNX Runtime Mobile for RTMPose (with CoreML EP for ANE acceleration)
  pod 'onnxruntime-mobile-c', '1.18.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
